export const refs = {
  statusDot: document.getElementById("statusDot"),
  statusTextEl: document.getElementById("statusText"),
  createBtn: document.getElementById("createSession"),
  sessionCodeIn: document.getElementById("sessionCode"),
  joinBtn: document.getElementById("joinSession"),
  sessionBarEl: document.getElementById("sessionBar"),
  apkBarEl: document.getElementById("apkBar"),
  pairQrEl: document.getElementById("pairQr"),
  qrHintEl: document.getElementById("qrHint"),
  pairLinkEl: document.getElementById("pairLink"),
  copyBtn: document.getElementById("copyPairLink"),
  qrBlockEl: document.getElementById("qrBlock"),
  linkedBanner: document.getElementById("linkedBanner"),
  linkedDevice: document.getElementById("linkedDevice"),
  cNameIn: document.getElementById("contactName"),
  cPhoneIn: document.getElementById("contactPhone"),
  cNoteIn: document.getElementById("contactNote"),
  addContactBtn: document.getElementById("addContact"),
  exportWordBtn: document.getElementById("exportWordBtn"),
  cBodyEl: document.getElementById("contactsBody"),
  contactsSec: document.getElementById("contactsSection"),
  contactsPaginationEl: document.getElementById("contactsPagination"),
  prevPageBtn: document.getElementById("prevPageBtn"),
  nextPageBtn: document.getElementById("nextPageBtn"),
  pageInfoEl: document.getElementById("pageInfo"),
  calledContactsValueEl: document.getElementById("calledContactsValue"),

  callModalEl: document.getElementById("callModal"),
  callRingEl: document.getElementById("callRing"),
  callKickerEl: document.getElementById("callKicker"),
  callNameEl: document.getElementById("callName"),
  callNumberEl: document.getElementById("callNumber"),
  callNoteEl: document.getElementById("callNote"),
  callBadgeEl: document.getElementById("callStateBadge"),
  callDurEl: document.getElementById("callDuration"),
  micBadgeEl: document.getElementById("micBadge"),
  apkAckBadgeEl: document.getElementById("apkAckBadge"),
  muteBtnEl: document.getElementById("modalMuteBtn"),
  speakerBtnEl: document.getElementById("modalSpeakerBtn"),
  hangupBtnEl: document.getElementById("modalHangupBtn"),
  callHintEl: document.getElementById("callHint"),

  apkNameEl: document.getElementById("apkName"),
  apkMetaEl: document.getElementById("apkMeta"),
  apkDlBtn: document.getElementById("apkDownloadBtn"),
  apkVersionSelectEl: document.getElementById("apkVersionSelect"),
  apkHelpBtn: document.getElementById("apkInstallHelp"),
  installGuide: document.getElementById("installGuide"),

  tabWord: document.getElementById("tabWord"),
  tabUrl: document.getElementById("tabUrl"),
  panelWord: document.getElementById("importPanelWord"),
  panelUrl: document.getElementById("importPanelUrl"),
  importFileEl: document.getElementById("importFile"),
  importFileNameEl: document.getElementById("importFileName"),
  importUrlEl: document.getElementById("importUrl"),
  importUrlBtn: document.getElementById("importUrlBtn"),
  importPreview: document.getElementById("importPreview"),
  previewCountEl: document.getElementById("previewCount"),
  previewBody: document.getElementById("previewBody"),
  importConfirm: document.getElementById("importConfirmBtn"),
  importCancel: document.getElementById("importCancelBtn"),
  floatingAddContactBtn: document.getElementById("floatingAddContactBtn"),
  reminderFloatContainer: document.getElementById("reminderFloatContainer"),
  addContactModalEl: document.getElementById("addContactModal"),
  addCloseBtn: document.getElementById("addCloseBtn"),
  addSaveBtn: document.getElementById("addSaveBtn"),
  addNameInput: document.getElementById("addNameInput"),
  addPhoneInput: document.getElementById("addPhoneInput"),
  addNoteInput: document.getElementById("addNoteInput"),
  editModalEl: document.getElementById("editContactModal"),
  editCloseBtn: document.getElementById("editCloseBtn"),
  editSaveBtn: document.getElementById("editSaveBtn"),
  editNameInput: document.getElementById("editNameInput"),
  editPhoneInput: document.getElementById("editPhoneInput"),
  editNoteInput: document.getElementById("editNoteInput"),
  openQuotationBtn: document.getElementById("openQuotationBtn"),
  quotationModalEl: document.getElementById("quotationModal"),
  quotationCloseBtn: document.getElementById("quotationCloseBtn"),
  quotationItemsBodyEl: document.getElementById("quotationItemsBody"),
  quotationAddItemBtn: document.getElementById("quotationAddItemBtn"),
  quotationApplyIgvEl: document.getElementById("quotationApplyIgv"),
  quotationSubtotalEl: document.getElementById("quotationSubtotal"),
  quotationIgvEl: document.getElementById("quotationIgv"),
  quotationTotalEl: document.getElementById("quotationTotal"),
  quotationPreviewBtn: document.getElementById("quotationPreviewBtn"),
  quotationDownloadBtn: document.getElementById("quotationDownloadBtn"),
  quotationPreviewModalEl: document.getElementById("quotationPreviewModal"),
  quotationPreviewCloseBtn: document.getElementById("quotationPreviewCloseBtn"),
  quotationPreviewDownloadBtn: document.getElementById("quotationPreviewDownloadBtn"),
  quotationSendFeedbackEl: document.getElementById("quotationSendFeedback"),
  quotationPreviewFrameEl: document.getElementById("quotationPreviewFrame"),
  qDateEl: document.getElementById("qDate"),
  qCompanyEl: document.getElementById("qCompany"),
  qRucEl: document.getElementById("qRuc"),
  qPhoneEl: document.getElementById("qPhone"),
  qEmailEl: document.getElementById("qEmail"),
  qAddressEl: document.getElementById("qAddress"),
  quotationServicesDatalistEl: document.getElementById("quotationServicesDatalist"),
};

export function setStatus(msg, isActive = false) {
  refs.statusTextEl.textContent = msg;
  refs.statusDot.classList.toggle("active", isActive);
}

export function setBadge(state, callBadgeEl) {
  callBadgeEl.className = `badge state-${state}`;
  const labels = {
    dialing: "LLAMANDO...",
    ringing: "SONANDO",
    in_call: "EN LLAMADA",
    ended: "FINALIZADA",
    idle: "ESPERA",
    failed: "ERROR"
  };
  callBadgeEl.textContent = labels[state] || state.replace("_", " ");
}

export function setAckBadge(el, state, text) {
  el.className = `badge ${state ? `ack-${state}` : ""}`.trim();
  el.textContent = text || "APK · —";
}
